### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by dstathis** [canonical/cos-alerter#20]
### Enhancement Proposal

Docs are needed:
- [x] Proper code comments
- [x] Module and function docstrings
- [x] Commented config file example
- [x] *.md files
- [x]  Discourse post

**Comment by sed-i** [comment]
Some kind of a diagram would be nice too.

**Comment by dstathis** [comment]
> Some kind of a diagram would be nice too.

What would you like to see in such a diagram?
