### ISSUE TITLE
Authentication for /alive endpoint

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-alerter#57]
### Enhancement Proposal

Currently:
- client ID (potentially sensitive) is sent over the network, without native TLS support in cos-alerter this means sending sensitive data unencrypted
- even with HTTPS enabled, a malicious actor can send a valid client ID to the /alive endpoint and pretend to be an active alertmanager instance while the actual instance may be down

Potential solutions:
- TLS support + a pre-shared secret (password) included in the client POST requests sent to /alive (ins tead of sending  only client ID that may be easy to guess)
- sending a token in the POST request and mapping that token to a client ID in cos-alerter.yaml config
- mutual TLS (might be an overkill)

**Comment by lucabello** [comment]
We've implemented authentication using a client ID. Without TLS however this isn't secure; once TLS is implemented this can be closed.

**Comment by lucabello** [comment]
Closing this in favor of #59, so we can track the progress in a single place.
