### ISSUE TITLE
Avoid pagerduty alerts duplication

### ISSUE THREAD

**Issue by helgharbi** [canonical/cos-alerter#61]
### Enhancement Proposal

When using pagerduty_configs with alert manager alertmanager.

Raised pagerduty alerts are not using dedupication key to correlating triggers and resolves.
Causing a new alerts to be trigered every interval and alerts are never resolved.

See dedup_key usage [here](https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgx-send-an-alert-event):

> `dedup_key`  (String):  Deduplication key for correlating triggers and resolves

**Comment by sed-i** [comment]
In order to avoid duplicating alerts, the repeat interval key needs to be set to a large value to suppress additional messages.
As for `dedup_key` and resolution - these could be raised as a feature request for cos-alerter to add native pagerduty support.

**Comment by simskij** [comment]
> In order to avoid duplicating alerts, the repeat interval key needs to be set to a large value to suppress additional messages.

This is not a viable solution.

> As for dedup_key and resolution - these could be raised as a feature request for cos-alerter to add native pagerduty support.

However, this is :)
